### ISSUE TITLE
Handling non-specific observations

### ISSUE THREAD

**Issue by bsaul** [nc-minibbs/mbbs#106]
In #105, I'm redoing the ebird import and excluding non-specific observations (e.g. `waterfowl sp.`). It seems reasonable to me to exclude such observations, what about the following?

```r
  submission common_name                 count  year route  
  <chr>      <chr>                       <int> <dbl> <chr>  
1 S176800937 American/Fish Crow              1  2024 cthm-04
2 S140352313 Sharp-shinned/Cooper's Hawk     1  2023 dhrm-06
3 S140725277 American/Fish Crow              3  2023 dhrm-04
4 S178972100 American/Fish Crow              1  2024 orng-06
5 S88387957  Summer/Scarlet Tanager          1  2021 orng-08
6 S112251543 Summer/Scarlet Tanager          1  2022 orng-06
```

**Comment by IJBG** [comment]
I think these should also be excluded, like American/Fish Crow is essentially a `corvid sp.`. It is a shame to lose the data though, I suppose the alternative would be assigning it to the more common of the two species?

**Comment by IJBG** [comment]
Decision: leave them in, the user can handle filtering them out or otherwise assigning them if they need to. They're rare in the dataset and for our analysis ends, are excluded by filters
