### ISSUE TITLE
Handling cases of `X` Counts

### ISSUE THREAD

**Issue by bsaul** [nc-minibbs/mbbs#14]
@ahhurlbert: any thoughts on how should we handle the few cases where the count is `X`:

```
sub_id       date                    observers            common_name count
1  S8347869 2011-05-22                         <NA>                Mallard     X
2 S10953436 2012-06-10 Norman Budnitz, Mike Schultz      Northern Bobwhite     X
3 S10953436 2012-06-10 Norman Budnitz, Mike Schultz Eastern Whip-poor-will     X
4  S8347869 2011-05-22                         <NA>       Eastern Kingbird     X
5 S10953436 2012-06-10 Norman Budnitz, Mike Schultz       Kentucky Warbler     X
6  S6552240 2010-06-17                         <NA>        Prairie Warbler     X
```

From ebird help:

> Counting individual birds provides incredibly valuable data for understanding bird populations. Putting “X” only tells us the species was present - but there could be anywhere from 1 to 1,000,000! If you’re studying bird populations, knowing whether there were 40 or 40,000 individuals makes all the difference. Provide exact counts when you can, and your closest estimate when you can't.

**Comment by ahhurlbert** [comment]
I suggest scoring them all as 1, and adding a comment. If all other species on the checklist have a count, one possibility is some may have used X to denote something like "detected between stops or outside of the 3-minute window" or something like that. We could also email Norm and Mike and ask if they recall.

**Comment by bsaul** [comment]
👍🏼 . Sounds good. I'm creating a `count_raw` field to store the original values too.
