### ISSUE TITLE
data anomalies in 2004

### ISSUE THREAD

**Issue by ahhurlbert** [nc-minibbs/mbbs#22]
For a number of species, there are anomalously high values across many routes in 2004. Examples include: 
* Dickcissel
* Eastern screech owl
* House wren
* cormorant
* Field sparrow
* Fish crow
* etc.

**Comment by ahhurlbert** [comment]
Just figured out that for Chatham, the # of vehicles line on this page: https://minibbs.us/old-mbbs/2004chatham/chatham_2004 is duplicated again as the row of abundances for DCCO which made it so that all abundance values are not aligned with the appropriate species, but are shifted by one row.

Will get this fixed in the `mbbs/inst/extdata/chatham_2000-2009_from_website.csv` file, but will want @bsaul to make sure it propagates.

**Comment by ahhurlbert** [comment]
`chatham_2000-2009_from_website.csv` file now fixed.

**Comment by ahhurlbert** [comment]
FYI, I have spot-checked every web-table from old website and found no other errors. 

I think pre-eBird data is officially all clear now. 

I also added the file `mbbs/inst/extdata/orange_1999-2009_from_website.csv` which is the spot-checked data from `mbbs_orange_sitescrape_20190127.rds` but without records where count==0 from 2004 on.

**Comment by bsaul** [comment]
Import script updated and run ==> data updated in `0.3.0.0`.

**Comment by bsaul** [comment]
@ahhurlbert - I've update the mbbs site. Can you double check that the anomalies are corrected?

**Comment by ahhurlbert** [comment]
Yes, all of those anomalies look fixed!
