### ISSUE TITLE
removing errant Baltimore Oriole record from Chatham #12 in 2002

### ISSUE THREAD

**Issue by ahhurlbert** [nc-minibbs/mbbs#23]
In response to the below correspondence with Haven Wiley, I've changed the record of 9 Baltimore Orioles to 6 Orchard Orioles for Chatham Route 12 in 2002. The file `chatham_2000-2009_from_website.csv` has been updated, and data just needs to be propagated through for analyses and graphs.

Allen:
"Right now I'm looking into this observation of 9 Baltimore Orioles from Chatham Route 12 in 2002. (old website here  <https://minibbs.us/old-mbbs/2002chatham/routec12>). That same checklist lists Orchard Oriole with abundance 0. I'm thinking it's more likely that 9 refers to Orchard Orioles (which would still be a high count), and that Baltimore Orioles are a mistake. Do you have a take on this?"

Haven:
"In 2002 we ran two routes in Chatham, 12 (our long-term route) and 5 (which we ran for a few years because no one else would).  No BAOR recorded on either -- we have never recorded BAOR on an MBBS.

On route 12 in 2002 we had 6 OROR spread over 5 stops.  On route 5 we had 4 spread over 3 stops. That adds up to at least 10 on Chatham routes that year.  I apologize for the discrepancy between our records in the field and the summary for that year.  I hope there aren't many others.

In our experience, the OROR has definitely decreased, indeed almost disappeared, on our routes in the past decade or so."

**Comment by IJBG** [comment]
This issue can be closed now, dataset's gone through the 2023 update and so this change has been propagated through
