### ISSUE TITLE
"Rock Pigeon" and "Rock Pigeon (Feral Pigeon)"

### ISSUE THREAD

**Issue by ahhurlbert** [nc-minibbs/mbbs#24]
Older (pre-2010) entries for "Rock Pigeon" should be converted to "Rock Pigeon (Feral Pigeon)" which is the current common name accepted by eBird.

At the moment, each has its own trend.

**Comment by IJBG** [comment]
I changed the import_ebird on the branch I'm working on to clean the common names by removing all "()" from the ebird imports, to prevent issues like American Robin & American Robin (migratorius Group) being reported differently. Would you prefer making an exception to leave Rock Pigeon as Rock Pigeon (Feral Pigeon)?
