### ISSUE TITLE
duplicate data in eBird

### ISSUE THREAD

**Issue by ahhurlbert** [nc-minibbs/mbbs#37]
There seem to be instances in which there are multiple checklists for the same route-year. For at least some of these, the cause may be that the original observer (often Will Cook) actually shared the checklist with the mbbs eBird account in addition to the checklists that were scraped from the website and manually added. But in some cases, the values do not agree. Here are the examples from the mbbsorangenc account (mbbsdurhamnc and mbbschathamn checklists should be checked for similar duplicates):

- Orange 4 in 2004: https://ebird.org/checklist/S23455269 and https://ebird.org/checklist/S6659296
- Orange 4 in 2005: https://ebird.org/checklist/S6659351 and https://ebird.org/checklist/S6659606 
- Orange 5 in 2005: https://ebird.org/checklist/S6659365 and https://ebird.org/checklist/S23455267 and https://ebird.org/checklist/S6659305 (basically same checklists but off by 2 individuals total, and one doesn't include 0's that were imported by spreadsheet, one probably shared/entered by Will Cook [more trusted] vs other scraped from website)
- Orange 10 in 2005
- Orange 5 in 2006, 2007, 2008, 2009
- Orange 6 in 2008

(Note there are some duplicate route-years in a few cases (esp by Haven Wiley) because the protocol for awhile was to submit a separate nocturnal pre-survey checklist. Thus they are not true duplicates because they typically start at 5:10 whereas the actual checklist starts at 5:25 or 5:30.)

**Comment by ahhurlbert** [comment]
To be clear, it seems that in our own analysis we ignore eBird data pre-2009 (or is it 2010?) and only use the old website-based data for that period. However, the following tasks would be useful

- eBird accounts should be cleaned of duplicate surveys
- cases in which the duplicate checklists differ should be looked into, and in some cases, we will want to correct the website-based scraped data
- eventually we will want to make sure all historical MBBS surveys are entered into eBird (for eBird's sake, not for ours)

**Comment by IJBG** [comment]
Create text document to keep in the repository that has cleaning actions we've taken on ebird ie: removed checklist x because confirmed other checklist more accurate 
Markdown document
Checklists will be removed from ebird, but still available from the github previous ebird downloads
