### ISSUE TITLE
@Exports -> @returns

### ISSUE THREAD

**Issue by IJBG** [nc-minibbs/mbbs#59]
find R/ functions that are incorrectly using "@"Exports and change them to "@"returns

**Comment by bsaul** [comment]
FWIW (this might be why you opened the issue), in terms of `Roxygen` comments, `#' @exports` is a directive to make the function available to library users (i.e. when the package is build a function tagged with `@export` is added as an `export` in the `NAMESPACE` file automatically. `#' @returns` is simply a documentation directive to tell users what the function is supposed to return when called.

**Comment by IJBG** [comment]
Yep! I overused it in process_observers :)
