### ISSUE TITLE
Hardcoded Removals

### ISSUE THREAD

**Issue by IJBG** [nc-minibbs/mbbs#77]
Removal of sub_ID = S46296942 is hard-coded into `R/prepare_stop_level_data` 's function `prepare_to_process` to keep a pre-dawn owling checklist from stopping the function (doesn't meet species_comment processing data requirements of having 20 stops) remove this hard-code.

` # Remove pre-dawn owling checklist
 filter(sub_id != "S46296942")`

All hard coded removals should be in just one place. This is in I think in import_ebird_data.

**Comment by bsaul** [comment]
I think the submission should be added to the [`excluded_submissions.yml`](https://github.com/nc-minibbs/mbbs/blob/master/inst/excluded_submissions.yml) file.

**Comment by bsaul** [comment]
This was completed in #54, correct?

**Comment by bsaul** [comment]
I.e. [here](https://github.com/nc-minibbs/mbbs/pull/54/files#diff-e95ce6b4c344434a949100244818d224ec9ad0992086bf00322875b4e6a50104R51)

**Comment by bsaul** [comment]
@IJBG - was this completed?

**Comment by IJBG** [comment]
Yep!
